- .circleci/config.yml
The split docker build/publish jobs are now in the HMPPS orb - just
testing them out...
> Test with new HMPPS orb

- .circleci/config.yml
Reverts ministryofjustice/manage-recalls-ui#29
> Revert "Test with new HMPPS orb"

- README.md
- integration_tests/integration/assess-recall.spec.js
- integration_tests/pages/assessRecall.js
- server/routes/handlers/assessRecall.ts
- server/routes/index.ts
- server/views/pages/assessRecall.njk
- server/views/pages/recallList.njk
https://dsdmoj.atlassian.net/browse/PUD-218
> Assess recall page

- README.md
readme set-up note updates re. nvm npm node only
> readme nvm npm node updates

- integration_tests/integration/recall-list.spec.js
- integration_tests/pages/recallsList.js
- package.json
- scripts/start-for-integration-tests.sh
- server/views/pages/newRecall.njk
- server/views/pages/recallList.njk
- server/views/pages/recallType.njk
> PUD-106 fix 'View' links in To do list

- fake-manage-recalls-api/stubs/__files/get-recall.json
- integration_tests/integration/assess-recall.spec.js
- integration_tests/integration/book-recall.spec.js
- integration_tests/pages/recallPrisonPolice.js
- pact/pacts/manage-recalls-ui-manage-recalls-api.json
- server/routes/handlers/book/lastRelease.test.ts
- server/routes/handlers/book/lastRelease.ts
- server/routes/handlers/book/prisonPolice.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.ts
- server/routes/index.ts
- server/views/pages/assessRecall.njk
- server/views/pages/recallPrisonPolice.njk
- server/views/pages/uploadDocuments.njk
https://dsdmoj.atlassian.net/browse/PUD-248
> PUD-248 local police

- package-lock.json
- package.json
- server/routes/handlers/book/lastRelease.test.ts
- server/routes/handlers/helpers/index.test.ts
- server/routes/handlers/helpers/index.ts
- server/views/pages/recallLastRelease.njk
- don't apply daylight saving correction for dates, only date-times
- add missing subheading to sentence page
- remove nodemon, it wasn't working with ts-node
> PUD-415 date correction fix

- server/@types/index.d.ts
- server/config.ts
- server/data/prisonRegisterClient.test.ts
- server/data/prisonRegisterClient.ts
- server/data/restClient.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.test.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.ts
- simple client to fetch prison list from prison register API
- only fetch prison list for the pages that use it
> PUD-137 - Fetch prison list from prison register, add to res.locals

- pact/pacts/manage-recalls-ui-manage-recalls-api.json
- server/@types/manage-recalls-api/models/RecallResponse.ts
- server/@types/manage-recalls-api/models/UpdateRecallRequest.ts
- server/clients/manageRecallsApi/updateRecall.pact.test.ts
- server/routes/handlers/helpers/index.ts
- server/views/pages/assessDecision.njk
- server/views/pages/recallProbationOfficer.njk
- clean up pact tests, remove recallLength
> PUD-144: Add data-qa tag for recall length question 

- integration_tests/pages/recallPrisonPolice.js
- server/config.ts
- server/views/pages/recallPrisonPolice.njk
- mark as not required to be specified in production, because the default endpoint works for all envs
> Config for prison register

- feature.env
- integration_tests/integration/assess-recall.spec.js
- integration_tests/mockApis/mockResponses.js
- integration_tests/mockApis/mockResponses/prisonRegister.json
- integration_tests/mockApis/prisonRegisterApi.js
- integration_tests/pages/assessRecallPrison.js
- integration_tests/plugins/index.js
- server/@types/index.d.ts
- server/@types/manage-recalls-api/models/RecallResponse.ts
- server/@types/manage-recalls-api/models/UpdateRecallRequest.ts
- server/routes/handlers/assess/assessDecision.test.ts
- server/routes/handlers/assess/assessDecision.ts
- server/routes/handlers/assess/assessPrison.ts
- server/routes/index.ts
- server/utils/nunjucksFunctions.test.ts
- server/utils/nunjucksFunctions.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/assessPrison.njk
- server/views/pages/recallIssuesNeeds.njk
- server/views/pages/recallProbationOfficer.njk
- render prison list to 'Local police force' page in book recall flow
- nunjucks helper function to provide list of options for select / dropdowns (apply to existing selects)
> PUD-137 - Render prison list

- integration_tests/integration/book-recall.spec.js
- integration_tests/pages/assessRecallPrison.js
- integration_tests/pages/recallSentenceDetails.js
- server/data/prisonRegisterClient.test.ts
- server/data/prisonRegisterClient.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.ts
- server/views/pages/assessPrison.njk
- server/views/pages/recallSentenceDetails.njk
https://dsdmoj.atlassian.net/browse/PUD-318
> PUD-318 - Fit autocomplete component to current prison and releasing prison

- integration_tests/integration/assess-recall.spec.js
- integration_tests/integration/book-recall.spec.js
- integration_tests/pages/assessRecallEmail.js
- integration_tests/pages/page.js
- integration_tests/pages/recallRequestReceived.js
- server/routes/handlers/assess/assessEmail.ts
- server/routes/handlers/assess/assessPrison.ts
- server/routes/handlers/helpers/getFormValues.test.ts
- server/routes/handlers/helpers/getFormValues.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.ts
- server/routes/index.ts
- server/views/pages/assessDecision.njk
- server/views/pages/assessEmail.njk
- server/views/pages/assessRecall.njk
- server/views/partials/layout.njk
> PUD-122 - when was recall notification emailed page

- fake-manage-recalls-api/stubs/__files/get-recall.json
- integration_tests/integration/assess-recall.spec.js
- integration_tests/integration/create-dossier.spec.js
- integration_tests/mockApis/manageRecallsApi.js
- integration_tests/plugins/index.js
- pact/pacts/manage-recalls-ui-manage-recalls-api.json
- server/routes/handlers/helpers/getFormValues.test.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.ts
- server/utils/nunjucksFunctions.ts
- server/views/pages/assessRecall.njk
- check email downloads
- split assess recall test into two
- fix date time formatter - apply daylight saving correctly
> PUD-122 download email integration test

- integration_tests/integration/assess-recall.spec.js
- integration_tests/pages/assessRecallEmail.js
- server/routes/handlers/assess/assessEmail.ts
- server/routes/handlers/assess/helpers/validateEmail.test.ts
- server/routes/handlers/assess/helpers/validateEmail.ts
- server/views/pages/assessEmail.njk
- server/views/pages/recallRequestReceived.njk
- server/views/pages/recallSentenceDetails.njk
Fixes the issues in https://dsdmoj.atlassian.net/browse/PUD-122?focusedCommentId=172789
Also, server-side check that only .msg files. can be uploaded
> PUD-122 - upload file extensions; error message

- server/@types/index.d.ts
- server/routes/handlers/assess/getRecallNotificationPdf.test.ts
- server/routes/handlers/assess/getRecallNotificationPdf.ts
- server/routes/handlers/recallList.test.ts
- server/routes/handlers/recallList.ts
Change to lastname first.
Also, add a unit test for recalls list handler
> PUD-488 name format

- integration_tests/mockApis/manageRecallsApi.js
- integration_tests/plugins/index.js
- pact/pacts/manage-recalls-ui-manage-recalls-api.json
> PUD-83: Rename revocationOrder endpoint to recallNotification

- fake-manage-recalls-api/stubs/__files/get-recall.json
- integration_tests/integration/create-dossier.spec.js
- integration_tests/pages/dossierDownload.js
- pact/pacts/manage-recalls-ui-manage-recalls-api.json
- server/@types/manage-recalls-api/models/RecallResponse.ts
- server/@types/manage-recalls-api/models/UpdateRecallRequest.ts
- server/routes/handlers/dossier/helpers/validateDossierDownload.test.ts
- server/routes/handlers/dossier/helpers/validateDossierDownload.ts
- server/routes/handlers/helpers/getFormValues.test.ts
- server/routes/handlers/helpers/getFormValues.ts
- server/routes/index.ts
- server/views/pages/dossierDownload.njk
https://dsdmoj.atlassian.net/browse/PUD-168
> PUD-168 - Download dossier - confirm dossier checked

- server/routes/handlers/helpers/handleRecallFormPost.test.ts
- server/routes/handlers/helpers/handleRecallFormPost.ts
> On API error, reload the page and show message

- server/views/components/document-download-link/index.scss
- server/views/components/document-download-link/template.njk
- server/views/pages/dossierDownload.njk
> PUD-535 - Dossier download - link name & style

- Dockerfile
- server/app.ts
This will allow us to match up errors to reported releases.
ref PUD-601
> Set the SENTRY_RELEASE env variable

- server/clients/manageRecallsApi/manageRecallsApiClient.ts
- server/routes/handlers/user/userDetails.ts
- server/routes/index.ts
- server/views/pages/userDetails.njk
> PUD-540 - User details form

- fake-manage-recalls-api/stubs/__files/get-recall.json
- integration_tests/integration/assess-recall.spec.js
- integration_tests/integration/book-recall.spec.js
- integration_tests/pages/recallCheckAnswers.js
- integration_tests/pages/uploadDocuments.js
- pact/pacts/manage-recalls-ui-manage-recalls-api.json
- server/@types/index.d.ts
- server/routes/handlers/book/recallUploadDocuments.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.test.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.ts
- server/routes/index.ts
- server/views/pages/recallCheckAnswers.njk
https://dsdmoj.atlassian.net/browse/PUD-105
> PUD-105 - Book recall - check answers page

- server/@types/index.d.ts
- server/routes/handlers/book/helpers/index.ts
- server/routes/handlers/book/recallUploadDocuments.test.ts
- server/routes/handlers/book/recallUploadDocuments.ts
- server/routes/handlers/helpers/index.test.ts
- server/routes/handlers/helpers/index.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.test.ts
The stored filenames should be the ones specified in PUD-322 - https://dsdmoj.atlassian.net/browse/PUD-629
The sort order of docs on the summary page should match the order on the upload page - https://dsdmoj.atlassian.net/browse/PUD-630
> PUD-322 upload docs - sort order, filenames

- pact/pacts/manage-recalls-ui-manage-recalls-api.json
- server/@types/index.d.ts
- server/data/hmppsAuthClient.test.ts
- server/data/hmppsAuthClient.ts
- server/index.ts
- server/routes/handlers/book/helpers/validateCheckAnswers.test.ts
- server/routes/handlers/book/helpers/validateCheckAnswers.ts
- server/routes/handlers/book/recallUploadDocuments.ts
- server/routes/handlers/helpers/handleRecallFormPost.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.test.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.ts
- server/routes/index.ts
- server/routes/testutils/appSetup.ts
- server/services/userService.test.ts
- server/services/userService.ts
- server/views/pages/assessRecall.njk
- server/views/pages/recallCheckAnswers.njk
- server/views/pages/recallDocuments.njk
also, check your answers - send 'booked by' user on submit
> PUD-540 - user details refactor

- server/views/pages/assessRecall.njk
- server/views/pages/recallCheckAnswers.njk
- fix row format in assess recall
- show No if no detail for contraband / vulnerability
- capitalise Local Delivery Unit
> PUD-540 - content changes - small additions

- integration_tests/integration/book-recall.spec.js
- integration_tests/integration/create-dossier.spec.js
- integration_tests/integration/find-person.spec.js
- integration_tests/pages/page.js
- package-lock.json
- package.json
- server/routes/handlers/book/helpers/validateProbationOfficer.test.ts
- server/routes/handlers/book/helpers/validateProbationOfficer.ts
- server/routes/handlers/book/helpers/validateSentenceDetails.test.ts
- server/routes/handlers/book/helpers/validateSentenceDetails.ts
- server/routes/handlers/dossier/helpers/validateDossierLetter.test.ts
- server/routes/handlers/dossier/helpers/validateDossierLetter.ts
- server/routes/handlers/helpers/index.test.ts
- server/routes/handlers/helpers/index.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.ts
- server/routes/handlers/person/findPerson.test.ts
- server/routes/handlers/person/helpers/validateFindPerson.test.ts
- server/routes/handlers/person/helpers/validateFindPerson.ts
- server/views/pages/dossierDownload.njk
- server/views/pages/dossierLetter.njk
- server/views/pages/findPerson.njk
- server/views/pages/recallProbationOfficer.njk
- server/views/pages/recallSentenceDetails.njk
- ability to render data into error messages eg 'Enter the NOMIS that Wesley Holt is being held under'
- use error messages from Jason spreadsheet for probation, letter, sentence details. Summary and field errors will always match now
- bump Cypress version
> PUD-608 - error messages

- integration_tests/integration/assess-recall.spec.js
- integration_tests/integration/book-recall.spec.js
- server/@types/index.d.ts
- server/routes/handlers/assess/helpers/validateRecallNotificationEmail.test.ts
- server/routes/handlers/assess/helpers/validateRecallNotificationEmail.ts
- server/routes/handlers/book/helpers/validateRecallRequestReceived.test.ts
- server/routes/handlers/book/helpers/validateRecallRequestReceived.ts
- server/routes/handlers/book/helpers/validateSentenceDetails.ts
- server/routes/handlers/dossier/helpers/validateDossierEmail.test.ts
- server/routes/handlers/dossier/helpers/validateDossierEmail.ts
- server/routes/handlers/helpers/confirmEmailSent.test.ts
- server/routes/handlers/helpers/dates.test.ts
- server/routes/handlers/helpers/dates.ts
- server/views/pages/assessEmail.njk
- server/views/pages/dossierEmail.njk
- refactor date validation to return granular errors
- update recall request received validation to render granular errors
- other error messages updated in dossier/recall email
> PUD-497 - date validations

- integration_tests/integration/todo-recalls-list.spec.js
- integration_tests/pages/recallsList.js
- server/views/partials/recallActionLink.njk
NB: the new value of the status enum from the API is not included as it isn't yet defined on main - but I don't see any impact of that either.
> PUD-719  FE: add action link for new status, DOSSIER_ISSUED

- server/routes/handlers/assess/helpers/validateRecallNotificationEmail.ts
- server/routes/handlers/book/helpers/validateRecallRequestReceived.test.ts
- server/routes/handlers/book/helpers/validateRecallRequestReceived.ts
- server/routes/handlers/dossier/helpers/validateDossierEmail.test.ts
- server/routes/handlers/dossier/helpers/validateDossierEmail.ts
- server/routes/handlers/helpers/allowedUploadExtensions.ts
- server/routes/handlers/helpers/emailUploadForm.test.ts
- server/routes/handlers/helpers/emailUploadForm.ts
- server/routes/handlers/helpers/uploadStorage.ts
- server/utils/nunjucksFunctions.ts
- validate request before saving file to API
> PUD-691 - upload recall request email - validate before save

- integration_tests/integration/book-recall.spec.js
- integration_tests/pages/page.js
- server/@types/index.d.ts
- server/middleware/parseUrlParams.test.ts
- server/middleware/parseUrlParams.ts
- server/routes/handlers/helpers/handleRecallFormPost.test.ts
- server/routes/handlers/helpers/handleRecallFormPost.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.test.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.ts
- server/routes/index.ts
- server/routes/testutils/mockRequestUtils.ts
- server/utils/nunjucksFunctions.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/recallPreConsName.njk
- server/views/partials/personDetails.njk
- middleware to parse out 'fromPage' query string param and use to redirect back to check answers page
- add a Change link for pre-cons name on check answers page
> PUD-633 - Allow redirect back to check answers page

- server/@types/index.d.ts
- server/routes/handlers/helpers/emailUploadForm.test.ts
- server/routes/handlers/helpers/emailUploadForm.ts
- server/utils/nunjucksFunctions.test.ts
- server/utils/nunjucksFunctions.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/recallRequestReceived.njk
- server/views/partials/personDetails.njk
- server/views/partials/recallRequestDetails.njk
Also, add change links for recall request on check answers page
> PUD-633 - check answers - extend URL helpers to deal with CSRF query strings

- integration_tests/integration/book-recall.spec.js
- integration_tests/pages/recallCheckAnswers.js
- server/views/pages/recallDocuments.njk
- server/views/partials/probationDetails.njk
- server/views/partials/sentenceDetails.njk
Assertions for every change link
> PUD-633 - integration test

- integration_tests/integration/book-recall.spec.js
- server/@types/index.d.ts
- server/routes/handlers/book/documentTypes.ts
- server/routes/handlers/book/helpers/index.ts
- server/routes/handlers/book/helpers/validateIssuesNeeds.test.ts
- server/routes/handlers/book/helpers/validateIssuesNeeds.ts
- server/routes/handlers/book/helpers/validateUploadDocuments.test.ts
- server/routes/handlers/book/helpers/validateUploadDocuments.ts
- server/routes/handlers/book/recallUploadDocuments.test.ts
- server/routes/handlers/helpers/index.test.ts
- server/routes/handlers/helpers/viewWithRecallAndPerson.test.ts
- use lowercase for document types in sentences - "Select a part A report"
- "more detail" messages for vulnerability / contraband
> PUD-456 book messages tweaks

- server/views/pages/viewFullRecall.njk
- server/views/partials/additionalLicenceConditions.njk
- server/views/partials/custodyDetails.njk
- server/views/partials/recallDetails.njk
To match the prototype - https://hmpps-manage-recalls-prototype.herokuapp.com/view-recall/recall-information
> PUD-739 - View recall content tweaks

- server/views/pages/assessConfirmation.njk
> PUD-801 - Assess confirmation page copy

- server/views/pages/assessRecall.njk
PUD-783  UI: present Know my Target (Assessment) - styling vertical alignment (match to dossierRecallInformation.njk)
> PUD-783  UI: present Know my Target (Assessment) - styling vertical

- server/views/partials/personDetails.njk
- server/views/partials/recallDetails.njk
- server/views/partials/sentenceDetails.njk
Keep null checks for status to be backwards compatible until API is updated
> PUD-910: Add BEING_BOOKED_ON status

- integration_tests/integration/todo-recalls-list.spec.js
- integration_tests/pages/page.js
- server/views/pages/recallList.njk
- server/views/partials/custodyDetails.njk
- server/views/partials/recallDetails.njk
- custody - different nomsnumber
- recall details - licence breached, assessed by
> Dossier in progress - add missing data to recall information page

- server/errorHandler.test.ts
- server/errorHandler.ts
- server/views/pages/error-404.njk
- server/views/pages/error.njk
> PUD-905 app error messages

- .circleci/config.yml
- helm_deploy/values-manage-recalls-dev.yaml
This deploys the application to both the `ppud-replacement-dev` and
`manage-recalls-dev` namespaces.
ref PUD-1091
> Deploy to `manage-recalls-dev`

- .circleci/config.yml
- helm_deploy/values-dev.yaml
- helm_deploy/values-manage-recalls-preprod.yaml
This also starts deploying to `manage-recalls-preprod`
> `manage-recalls-dev` is the default dev namespace

- .circleci/config.yml
- helm_deploy/manage-recalls-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-manage-recalls-prod.yaml
- helm_deploy/values-preprod.yaml
... and start deploying to `manage-recalls-prod` in parallel.
ref PUD-1095
> Complete preprod migration to `manage-recalls-preprod`

- assets/sass/local.scss
- integration_tests/integration/change-history.spec.js
- integration_tests/pages/changeHistory.js
- integration_tests/pages/page.js
- server/@types/index.d.ts
- server/routes/handlers/helpers/dates/convert.ts
- server/routes/handlers/helpers/index.test.ts
- server/routes/handlers/helpers/index.ts
- server/routes/index.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/changeHistory.njk
- server/views/pages/recallList.njk
- server/views/partials/layout.njk
- server/views/partials/recallInformationHeading.njk
Also adds some cypress helpers including one to click on a PDF document link and verify the file contents
> PUD-767 document history

- logger.ts
- server/middleware/appInsightsOperationId.ts
- server/middleware/requestLogging.ts
comments on https://dsdmoj.atlassian.net/browse/PUD-1113
> PUD-1113 - Request logging changes

- package-lock.json
- package.json
should fix https://github.com/ministryofjustice/manage-recalls-ui/security/dependabot/package-lock.json/json-schema/open
> Bump cypress to version 9

- assets/js/document-upload.js
Will be covered at E2E test level.
> Doc upload button change event firing multiple times, so action only if file included in event

- server/@types/documents.d.ts
- server/@types/index.d.ts
- server/routes/handlers/documents/documentCategories.ts
- server/routes/handlers/documents/download/helpers/decorateAllDocTypes.ts
- server/routes/handlers/documents/download/helpers/decorateDocs.test.ts
- server/routes/handlers/documents/download/helpers/decorateDocs.ts
- server/routes/handlers/documents/download/helpers/getVersionedUpload.ts
- server/routes/handlers/documents/upload/helpers/allowedUploadExtensions.ts
- server/routes/handlers/documents/upload/validations/validateDocuments.ts
- server/routes/handlers/user/helpers/validateUserDetails.ts
- server/views/pages/newGeneratedDocumentVersion.njk
- server/views/partials/uploadedDocumentsStatus.njk
- split function up
- better naming of vars / functions
- add property for versioned generated doc
> PUD-1133 - Decorate docs refactor

- integration_tests/integration/documents-upload.spec.js
- server/routes/handlers/documents/categorise/categoriseFiles.test.ts
- server/routes/handlers/documents/categorise/helpers/index.ts
- server/routes/handlers/documents/categorise/validations/validateCategories.test.ts
- server/routes/handlers/documents/categorise/validations/validateCategories.ts
- server/routes/handlers/helpers/index.test.ts
- server/routes/handlers/helpers/index.ts
- server/utils/nunjucksFunctions.ts
- server/utils/nunjucksSetup.ts
- server/views/partials/uploadedDocuments.njk
- server/views/partials/uploadedDocumentsStatus.njk
- allow upload of more than one Other doc
- on recall info page, show Change link for uncategorised docs
- for a duplicate category error, set the category dropdown to the chosen (duplicate) category
> PUD-948 - misc upload document fixes

- integration_tests/integration/generated-documents.spec.js
- server/views/pages/changeHistory.njk
- server/views/partials/generatedDocuments.njk
also, for generated doc change links, return user to correct anchor point
> Change history - add subheadings

- server/views/pages/changeHistoryForDocument.njk
> PUD-1073 update to change history for document template

- pact/addMissingDocumentRecord.pact.test.ts
- pact/getRecall.pact.test.ts
- pact/pacts/manage-recalls-ui-manage-recalls-api.json
PUD-1268  Add missing document record tests to PACT: UI update
> PUD-1268  Add missing document record tests to PACT

- server/routes/handlers/change-history/helpers/recallFieldList.ts
> PUD-1301 - Show licence name in change history

- server/routes/handlers/documents/generated/createGeneratedDocument.test.ts
- server/routes/handlers/documents/generated/createGeneratedDocument.ts
> PUD-1251 - On the initial download of recall notification, dossier, letter, prevent multiple copies being created

- server/routes/handlers/book/helpers/validateIssuesNeeds.test.ts
- server/routes/handlers/book/helpers/validateIssuesNeeds.ts
- server/routes/handlers/book/helpers/validatePreConsName.test.ts
- server/routes/handlers/book/helpers/validatePreConsName.ts
- server/routes/handlers/dossier/helpers/validateDossierLetter.test.ts
- server/routes/handlers/dossier/helpers/validateDossierLetter.ts
> PUD-1345 - Set detail fields to empty string if No is chosen

- integration_tests/integration/assess-recall.spec.js
- integration_tests/integration/book-not-in-custody.spec.js
- integration_tests/integration/book-recall.spec.js
- integration_tests/integration/change-history.spec.js
- integration_tests/integration/create-dossier.spec.js
- integration_tests/integration/find-person.spec.js
- integration_tests/integration/generated-documents.spec.js
- integration_tests/integration/todo-recalls-list.spec.js
- integration_tests/integration/upload-documents-categories.spec.js
- integration_tests/integration/upload-documents.spec.js
- integration_tests/integration/uploaded-document-versions.spec.js
- integration_tests/integration/user-details.spec.js
- integration_tests/integration/view-recall.spec.js
- integration_tests/support/commands.js
- integration_tests/support/mock-api.js
- login-related mocks are centralised
- some tests merged where possible to speed up the suite
> PUD-1346 - Cypress - merge tests and refactor mock use / login

- fake-manage-recalls-api/stubs/__files/get-recall.json
- pact/getRecall.pact.test.ts
- pact/pacts/manage-recalls-ui-manage-recalls-api.json
PUD-1360  PACT: ensure coverage is in place for non-empty list of lastKnownAddresses: UI
Ready for review - but I won't merge 'til after I'm back from 🦷  work.
> PUD-1360  PACT: coverage for non-empty list of lastKnownAddresses

- server/data/restClient.ts
- server/data/tokenVerification.ts
Remove logging if token verification disabled
> Rest client - log full URL

- integration_tests/integration/book-not-in-custody.spec.js
- server/routes/handlers/book/helpers/validateAddressManual.test.ts
- server/routes/handlers/book/helpers/validateAddressManual.ts
- server/routes/handlers/helpers/getFormValues.test.ts
- server/routes/handlers/helpers/getFormValues.ts
- show saved value for lastKnownAddress
- trim whitespace from address inputs
> PUD-1258 - address changes

- integration_tests/integration/todo-recalls-list.spec.js
- integration_tests/support/commands.js
- server/routes/handlers/helpers/dates/sort.test.ts
- server/routes/handlers/helpers/dates/sort.ts
- server/routes/handlers/recallList.test.ts
- server/routes/handlers/recallList.ts
- server/views/pages/recallList.njk
This reverts commit 90bef4368ad55df651d98c8132f74c2b1fe0bb35.
> Revert "PUD-711 - Add a 'Not in custody' tab on recalls list (#551)"

- .circleci/config.yml
- scripts/run-e2e-tests.sh
I have a PR for the HMPPS orb open, but god knows when it'll get picked
up... This will make things more stable for now...
> Workaround for the E2E triggers timing out.

- assets/js/document-upload.js
- server/views/pages/recallDocuments.njk
- server/views/pages/recallFindAddressResults.njk
- server/views/pages/userDetails.njk
- server/views/partials/custodyDetails.njk
- server/views/partials/uploadedDocumentsStatus.njk
> PUD-1460 - a11y fixes

- integration_tests/integration/add-note.spec.js
- server/controllers/note/validators/validateAddNote.test.ts
- server/controllers/note/validators/validateAddNote.ts
Correct subject error message - tiny and will need to be copied to re-work, so merging w/out review.
> PUD-1489  Correct subject error message

- server/@types/index.d.ts
- server/controllers/assess/validators/validateDecision.test.ts
- server/controllers/assess/validators/validateDecision.ts
- server/controllers/assess/validators/validateRecallNotificationEmail.test.ts
- server/controllers/assess/validators/validateRecallNotificationEmail.ts
- server/controllers/book/validators/validateRecallRequestReceived.test.ts
- server/controllers/book/validators/validateRecallRequestReceived.ts
- server/controllers/documents/missing-documents/addMissingDocumentRecordFormHandler.ts
- server/controllers/documents/missing-documents/validators/validateMissingDocuments.test.ts
- server/controllers/documents/missing-documents/validators/validateMissingDocuments.ts
- server/controllers/documents/upload/formWithDocumentUploadHandler.test.ts
- server/controllers/documents/upload/formWithDocumentUploadHandler.ts
- server/controllers/documents/upload/helpers/allowedUploadExtensions.ts
- server/controllers/dossier/validators/validateDossierEmail.test.ts
- server/controllers/dossier/validators/validateDossierEmail.ts
- server/controllers/dossier/validators/validateNsyEmail.test.ts
- server/controllers/dossier/validators/validateNsyEmail.ts
- server/controllers/rescind/rescindFormHandler.ts
- server/controllers/rescind/validators/validateRescindDecision.test.ts
- server/controllers/rescind/validators/validateRescindDecision.ts
- server/controllers/rescind/validators/validateRescindRequest.test.ts
- server/controllers/rescind/validators/validateRescindRequest.ts
- server/routes/index.ts
- rename handler - will be used for any form with fields and a file upload
- move filename extension checking to validators
> PUD-1109 - Refactor email upload form handler, part 1

- server/controllers/documents/download/downloadDocumentOrEmail.test.ts
- server/controllers/documents/download/helpers/getMimeTypeForFileName.test.ts
- server/controllers/documents/download/helpers/getMimeTypeForFileName.ts
PUD-1558  An email file linked to a Note fails download (Exp. testing issue)
Fix and lack of side effects verified with local testing.
> PUD-1558  An email file linked to a Note fails download

- integration_tests/integration/find-person.spec.js
- package-lock.json
- package.json
- server/controllers/findPerson/findPerson.test.ts
- server/controllers/findPerson/findPerson.ts
- server/views/pages/findPerson.njk
Fix for PUD-1543 - Band 3 caseworker is able to assess a recall
Also, bump typescript, cypress, govuk-frontend
> PUD-1543 bug fix / version bumps

- .github/workflows/codeql-analysis.yml
- package-lock.json
- package.json
- server/app.ts
- server/views/pages/changeHistoryForDocument.njk
- server/views/pages/dossierNsyEmail.njk
- server/views/pages/newGeneratedDocumentVersion.njk
- server/views/pages/recallUploadDocumentVersion.njk
- server/views/partials/probationDetails.njk
This is a new service from github (code analysis from a security perspective) - might as well give it a try...
> Setup CodeQL analysis

- package-lock.json
ref: https://github.com/ministryofjustice/manage-recalls-ui/security/dependabot/5
> Update the minimist package to 1.2.6 to resolve CVE-2021-44906

- integration_tests/integration/add-note.spec.js
- server/views/partials/missingDocuments.njk
- server/views/partials/notes.njk
- server/views/partials/uploadedDocuments.njk
- hide Notes section in recall info, if there are none
- spacing / move link below subheading
> PUD-1382 - chase part B - amendments

- README.md
ref: https://mojdt.slack.com/archives/C02D2NEF9CJ/p1647956032772679
> Add the MoJ github repo compliance badge

- integration_tests/integration/recalls-list.spec.js
- server/controllers/recallsList/recallList.ts
- server/views/pages/recallList.njk
- changed AC - don't sort action column
> PUD-1550 - enable sortable tables / last updated column on recalls list page

- server/views/pages/dossierCheck.njk
- server/views/pages/recallList.njk
- server/views/partials/additionalLicenceConditions.njk
- server/views/partials/custodyDetails.njk
- server/views/partials/generatedDocuments.njk
- server/views/partials/issuesDetails.njk
- server/views/partials/missingDocuments.njk
- server/views/partials/notes.njk
- server/views/partials/probationDetails.njk
- server/views/partials/recallDetails.njk
- server/views/partials/rescinds.njk
- server/views/partials/revocationOrder.njk
- server/views/partials/sentenceDetails.njk
- server/views/partials/uploadedDocumentLink.njk
- server/views/partials/uploadedDocuments.njk
- server/views/partials/uploadedDocumentsStatus.njk
- server/views/partials/uploadedEmailLink.njk
Details / filenames might contain PII, so just hide all of them.
> PUD-1600 - Logrocket - redact all output details / filenames

- fake-manage-recalls-api/stubs/__files/get-recall.json
- integration_tests/integration/book-not-in-custody.spec.js
- integration_tests/integration/recalls-list.spec.js
- pact/pacts/manage-recalls-ui-manage-recalls-api.json
- server/@types/manage-recalls-api/models/RecallResponse.ts
- server/@types/manage-recalls-api/models/RecallResponseLite.ts
- server/controllers/recallsList/recallList.test.ts
- server/controllers/recallsList/recallList.ts
- server/controllers/utils/dates/sort.test.ts
- server/controllers/utils/dates/sort.ts
- server/controllers/utils/recallStatus.test.ts
- server/controllers/utils/recallStatus.ts
- server/views/pages/recallList.njk
This reverts commit aa675b44fc5d0f4c3f5cb5849364ddf8573ae1ad.
> PUD-1638 - re-open 'dossier check tab' PR

- .gitignore
- integration_tests/integration/assess-recall.spec.js
- integration_tests/integration/create-dossier.spec.js
- integration_tests/mockApis/manageRecallsApi.js
- integration_tests/support/commands.js
- server/controllers/documents/generated/createGeneratedDocument.test.ts
- server/controllers/documents/generated/createGeneratedDocument.ts
- server/views/components/document-download-link/template.njk
- server/views/pages/assessDownload.njk
- server/views/pages/dossierDownload.njk
For generated docs only, if creation fails (not retrieval from S3):
- Error message shown
- anchors to download link
- no error currently shown on download link component itself
- Continue button disabled until error resolves
> PUD0-1635 - download doc error

- fake-manage-recalls-api/stubs/__files/get-weekly-recalls-new.json
- integration_tests/integration/assess-recall.spec.js
- integration_tests/integration/primary-dossier.spec.js
- integration_tests/integration/reports.spec.js
- integration_tests/mockApis/manageRecallsApi.js
- integration_tests/plugins/index.js
- integration_tests/support/commands.js
- server/@types/manage-recalls-api/index.d.ts
- server/@types/manage-recalls-api/models/GetReportResponse.ts
- server/clients/manageRecallsApiClient.ts
- server/controllers/reports/downloadReport.ts
- server/controllers/reports/downloadReports.test.ts
- server/controllers/reports/index.ts
- server/routes/index.ts
- server/views/pages/reports.njk
PUD-1655 Weekly recalls new report Front End
Better for you to review this - rather than me just merge - IMO @jonnywyatt though maybe a bit late for this week now?
> PUD-1655 Weekly recalls new report Front End

- integration_tests/integration/secondary-dossier.spec.js
- server/controllers/secondaryDossier/validators/validateSeniorProbationOfficer.test.ts
- server/controllers/secondaryDossier/validators/validateSeniorProbationOfficer.ts
- server/views/partials/probationDetails.njk
also, enable functional email link on recall info page
> PUD-1663 - Correctly validate functional email

- server/app.ts
- server/middleware/setUpAuth.ts
- server/middleware/setUpHealthChecks.ts
- server/middleware/setUpSentry.ts
- server/middleware/setUpStaticResources.ts
- server/middleware/setUpWebSecurity.ts
- server/middleware/setUpWebSession.ts
Split up app.ts into separate files
> PUD-1287 - changes from typescript template

- integration_tests/integration/change-history.spec.js
- integration_tests/integration/find-person.spec.js
- integration_tests/integration/uploaded-documents-missing.spec.js
- server/controllers/reports/downloadReport.ts
- server/controllers/reports/downloadReports.test.ts
- server/controllers/userDetails/userDetails.test.ts
- server/controllers/userDetails/userDetails.ts
- server/middleware/checkUserDetailsExist.test.ts
- server/middleware/checkUserDetailsExist.ts
- server/routes/index.ts
Also, if user details missing, redirect from find person to user details page
> PUD-1682 - Sign out if user role is invalid (401 from API)

- .circleci/config.yml
Per: https://mojdt.slack.com/archives/C01S1M82NQ1/p1650451883073869?thread_ts=1650443607.554479&cid=C01S1M82NQ1
> TECH bump orb for veracode issue

- server/controllers/reports/index.ts
- server/controllers/serviceMetrics/index.ts
- server/views/partials/primaryNav.njk
NB: no test changes; I didn't find any tests for the nav bar or dependent on the properties it sets.
Navigation from the nav bar could be added to the tests for the newly linked features but that has not been added, given the project status.
> PUD-1714  Add reports & statistics links to home screen
